mailinglist/mailinglist-war/src/main/java/org/silverpeas/components/mailinglist/control/MailingListSessionController.java
/*
 * Copyright (C) 2000 - 2018 Silverpeas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * As a special exception to the terms and conditions of version 3.0 of
 * the GPL, you may redistribute this Program in connection with Free/Libre
 * Open Source Software ("FLOSS") applications as described in Silverpeas's
 * FLOSS exception. You should have received a copy of the text describing
 * the FLOSS exception, and it is also available here:
 * "https://www.silverpeas.org/legal/floss_exception.html"
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.silverpeas.components.mailinglist.control;

import org.silverpeas.components.mailinglist.service.model.MailingListService;
import org.silverpeas.core.web.mvc.controller.AbstractComponentSessionController;
import org.silverpeas.core.web.mvc.controller.ComponentContext;
import org.silverpeas.core.web.mvc.controller.MainSessionController;

public class MailingListSessionController extends AbstractComponentSessionController {

  /**
   * Standard Session Controller Constructeur
   * @param mainSessionCtrl The user's profile
   * @param componentContext The component's profile
   */
  public MailingListSessionController(MainSessionController mainSessionCtrl,
      ComponentContext componentContext) {
    super(mainSessionCtrl, componentContext,
        "org.silverpeas.mailinglist.multilang.mailinglistBundle",
        "org.silverpeas.mailinglist.settings.mailinglistIcons");
  }

  public boolean isModerated() {
    String param = getComponentParameterValue(MailingListService.PARAM_MODERATE);
    return param != null &&
        (Boolean.valueOf(param) || "Y".equalsIgnoreCase(param) || "YES".equalsIgnoreCase(param));
  }
}

mailinglist/mailinglist-war/src/main/java/org/silverpeas/components/mailinglist/servlets/AttachmentServlet.java
/*
 * Copyright (C) 2000 - 2018 Silverpeas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * As a special exception to the terms and conditions of version 3.0 of
 * the GPL, you may redistribute this Program in connection with Free/Libre
 * Open Source Software ("FLOSS") applications as described in Silverpeas's
 * FLOSS exception. You should have received a copy of the text describing
 * the FLOSS exception, and it is also available here:
 * "https://www.silverpeas.org/legal/floss_exception.html"
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.silverpeas.components.mailinglist.servlets;

import org.silverpeas.components.mailinglist.service.MailingListServicesProvider;
import org.silverpeas.components.mailinglist.service.model.beans.Attachment;
import org.silverpeas.components.mailinglist.service.model.beans.Message;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Iterator;

import static org.silverpeas.core.web.http.FileResponse.encodeInlineFilenameAsUtf8;

public class AttachmentServlet extends HttpServlet implements MailingListRoutage {
  private static final long serialVersionUID = -6066054163259803146L;

  @Override
  public void service(HttpServletRequest request, HttpServletResponse response)
      throws ServletException, IOException {
    RestRequest rest = new RestRequest(request);
    String messageId = rest.getElements().get(DESTINATION_MESSAGE);
    String attachmentId = rest.getElements().get(DESTINATION_ATTACHMENT);
    if (messageId == null || attachmentId == null) {
      return;
    }
    Message message = MailingListServicesProvider.getMessageService().getMessage(messageId);
    Iterator<Attachment> iter = message.getAttachments().iterator();
    Attachment file = null;
    boolean found = false;
    while (iter.hasNext() && !found) {
      Attachment attachment = iter.next();
      file = attachment;
      found = attachmentId.equals(attachment.getId());
    }
    if (found) {
      response.setContentType(file.getContentType());
      final String filename = encodeInlineFilenameAsUtf8(file.getFileName());
      response.setHeader("Content-Disposition", filename);
      long length = file.getSize();
      response.setHeader("Content-Length", String.valueOf(length));
      try (OutputStream out = response.getOutputStream();
           InputStream in = new FileInputStream(file.getPath())) {
        byte[] buffer = new byte[8];
        int c;
        while ((c = in.read(buffer)) != -1) {
          out.write(buffer, 0, c);
        }
      }
    }
  }
}

mailinglist/mailinglist-war/src/main/java/org/silverpeas/components/mailinglist/servlets/RssMailingListServlet.java
/*
 * Copyright (C) 2000 - 2018 Silverpeas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * As a special exception to the terms and conditions of version 3.0 of
 * the GPL, you may redistribute this Program in connection with Free/Libre
 * Open Source Software ("FLOSS") applications as described in Silverpeas's
 * FLOSS exception. You should have received a copy of the text describing
 * the FLOSS exception, and it is also available here:
 * "https://www.silverpeas.org/legal/floss_exception.html"
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.silverpeas.components.mailinglist.servlets;

import org.silverpeas.core.web.util.servlet.RssServlet;
import org.silverpeas.components.mailinglist.service.MailingListServicesProvider;
import org.silverpeas.components.mailinglist.service.model.MailingListService;
import org.silverpeas.components.mailinglist.service.model.MessageService;
import org.silverpeas.components.mailinglist.service.model.beans.MailingList;
import org.silverpeas.components.mailinglist.service.model.beans.Message;
import org.silverpeas.components.mailinglist.service.util.OrderBy;

import javax.inject.Inject;
import java.util.Collection;
import java.util.Date;

public class RssMailingListServlet extends RssServlet<Message> {

  @Inject
  private MailingListService mailingListService;
  @Inject
  private MessageService messageService;

  @Override
  public String getElementCreatorId(Message element) {
    return null;
  }

  @Override
  public String getExternalCreatorId(Message message) {
    return message.getSender();
  }

  @Override
  public Date getElementDate(Message message) {
    return message.getSentDate();
  }

  @Override
  public String getElementDescription(Message message, String userId) {
    return message.getSummary();
  }

  @Override
  public String getElementLink(Message message, String userId) {
    return MailingListServicesProvider.getNotificationFormatter().prepareUrl(message, false);
  }

  @Override
  public String getElementTitle(Message message, String userId) {
    return message.getTitle();
  }

  @Override
  public Collection getListElements(String instanceId, int nbReturned) {
    MailingList mailingList = mailingListService.findMailingList(instanceId);
    return messageService
        .listDisplayableMessages(mailingList, nbReturned, new OrderBy("sentDate", true));
  }
}

mailinglist/mailinglist-war/src/main/webapp/mailingList/jsp/check.jsp
<%--

    Copyright (C) 2000 - 2018 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<%@ page isELIgnored="false"%>
<%
response.setHeader("Cache-Control","no-store"); //HTTP 1.1
response.setHeader("Pragma","no-cache");        //HTTP 1.0
response.setDateHeader ("Expires",-1);          //prevents caching at the proxy server
%>

<%@ page import="org.silverpeas.core.util.MultiSilverpeasBundle"%>

<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.arraypanes.ArrayPane"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.arraypanes.ArrayLine"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.arraypanes.ArrayColumn"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.arraypanes.ArrayCellText"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.arraypanes.ArrayCellLink"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.iconpanes.IconPane"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.icons.Icon"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.tabs.TabbedPane"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.buttonpanes.ButtonPane"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.buttons.Button"%>
<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.board.Board"%>

<%@ page import="org.silverpeas.core.util.ResourceLocator"%>
<%@ page import="org.silverpeas.core.util.URLUtil"%>

<%@ page import="org.silverpeas.core.web.util.viewgenerator.html.Encode"%>
<%@ page errorPage="../../admin/jsp/errorpageMain.jsp"%>

mailinglist/mailinglist-war/src/main/webapp/mailingList/jsp/list.jsp
<%--

    Copyright (C) 2000 - 2018 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<%@ page isELIgnored="false"%>
<%@ include file="check.jsp"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://www.silverpeas.com/tld/viewGenerator" prefix="view"%>
<c:set var="componentId" value="${requestScope.componentId}" />
<c:set var="sessionController">Silverpeas_MailingList_<c:out value="${componentId}" />
</c:set>
<fmt:setLocale value="${sessionScope[sessionController].language}" />
<view:setBundle bundle="${requestScope.resources.multilangBundle}" />
<view:setBundle bundle="${requestScope.resources.iconsBundle}" var="icons" />
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><fmt:message key="mailingList.tab.list.title" /></title>
<view:looknfeel />
<c:if test="${requestScope.currentUserIsAdmin}">
  <script type="text/javascript">
    function deleteMessage(){
      if(confirm('<fmt:message key="mailingList.moderation.delete.confirm"/>')){
        document.removeMessage.submit();
      }
    }
  </script>
</c:if>
</head>
<body>
<fmt:message key="mailingList.icons.attachmentSmall" var="attachmentIcon" bundle="${icons}" />
<fmt:message key="mailingList.tab.list.title" var="listTabTitle" />
<fmt:message key="mailingList.tab.activity.title" var="activityTabTitle" />
<view:browseBar>
  <view:browseBarElt link="" label="${listTabTitle}" />
</view:browseBar>
<c:if test="${requestScope.currentUserIsAdmin}">
  <fmt:message key="mailingList.icons.message.delete.alt" var="deleteMessageAltText" />
  <fmt:message key="mailingList.icons.message.delete" var="deleteIconPath" bundle="${icons}" />
  <c:url var="deleteIcon" value="${deleteIconPath}" />
  <view:operationPane>
    <view:operation altText="${deleteMessageAltText}" icon="${deleteIcon}" action="${'javascript: deleteMessage();'}" />
  </view:operationPane>
</c:if>
<view:window>
  <c:choose>
    <c:when test="${requestScope.currentUserIsAdmin}">
      <c:set var="paginationColspan" value="5" />
    </c:when>
    <c:otherwise>
      <c:set var="paginationColspan" value="4" />
    </c:otherwise>
  </c:choose>
  <c:url var="activityAction" value="/Rmailinglist/${componentId}/Main" />
  <view:tabs>
    <view:tab label="${activityTabTitle}" action="${activityAction}" selected="false" />
    <view:tab label="${listTabTitle}" action="${'#'}" selected="true" />
    <c:if test="${(requestScope.currentUserIsAdmin || requestScope.currentUserIsModerator) && requestScope.currentListIsModerated}">
      <fmt:message key="mailingList.tab.moderation.title" var="moderationTabTitle" />
      <c:url var="moderationAction" value="/Rmailinglist/${componentId}/moderationList/${componentId}" />
      <view:tab label="${moderationTabTitle}" action="${moderationAction}" selected="false" />
    </c:if>
    <c:if test="${requestScope.currentUserIsAdmin}">
      <fmt:message key="mailingList.tab.users.title" var="usersTabTitle" />
      <c:url var="usersAction" value="/Rmailinglist/${componentId}/users/${componentId}" />
      <view:tab label="${usersTabTitle}" action="${usersAction}" selected="false" />
    </c:if>
    <c:if test="${requestScope.currentUserIsAdmin}">
      <fmt:message key="mailingList.tab.subscribers.title" var="subscribersTabTitle" />
      <c:url var="subscriberssAction" value="/Rmailinglist/${componentId}/subscription/${componentId}/subscription/put" />
      <view:tab label="${subscribersTabTitle}" action="${subscriberssAction}" selected="false" />
    </c:if>
  </view:tabs>
  <view:frame>
    <center><c:if test="${requestScope.currentUserIsAdmin}">
      <form id="removeMessage" name="removeMessage" method="DELETE" action="<c:url value="/Rmailinglist/${componentId}/destination/list/message/delete"/>">
    </c:if>
    <table width="98%" border="0" cellpadding="0" cellspacing="2">
      <tr>
        <td>
        <table id="list" class="tableArrayPane" width="100%" cellspacing="2" cellpadding="2" border="0">
          <tr>
            <c:if test="${requestScope.currentUserIsAdmin}">
              <td class="ArrayColumn" align="center">&nbsp;</td>
            </c:if>
            <td class="ArrayColumn" width="100%"><fmt:message key="mailingList.list.messages.title" /></td>
            <td class="ArrayColumn" align="center" nowrap="nowrap"><a
              href="<c:url value="/Rmailinglist/${componentId}/list/${componentId}">
                <c:param name="orderBy" value="attachmentsSize"/>
                <c:param name="ascendant"><c:choose><c:when test="${requestScope['attachmentsSize'] != null}"><c:out value="${requestScope['attachmentsSize']}" /></c:when><c:otherwise>true</c:otherwise></c:choose></c:param></c:url>"><fmt:message
              key="mailingList.list.attachments.title" /></a></td>
            <td class="ArrayColumn" align="center" nowrap="nowrap"><a
              href="<c:out value="${pageContext.request.contextPath}"/>/Rmailinglist/<c:out value="${componentId}"/>/list/<c:out value="${componentId}"/>?orderBy=sender&ascendant=<c:choose><c:when test="${requestScope['sender'] != null}"><c:out value="${requestScope['sender']}" /></c:when><c:otherwise>true</c:otherwise></c:choose>" /><fmt:message
              key="mailingList.list.sender.title" /></a></td>
            <td class="ArrayColumn" align="center" nowrap="nowrap"><a
              href="<c:out value="${pageContext.request.contextPath}"/>/Rmailinglist/<c:out value="${componentId}"/>/list/<c:out value="${componentId}"/>?orderBy=sentDate&ascendant=<c:choose><c:when test="${requestScope['sentDate'] != null}"><c:out value="${requestScope['sentDate']}" /></c:when><c:otherwise>true</c:otherwise></c:choose>" /><fmt:message
              key="mailingList.list.sentDate.title" /></a></td>
          </tr>
          <c:forEach items="${requestScope.currentMessageList}" var="message" varStatus="messageIndex">
            <c:set var="lineClass" value="ArrayCell" />
            <c:choose>
              <c:when test="${(messageIndex.index%2) == 0}">
                <c:set var="lineClass" value="ArrayCell" />
              </c:when>
              <c:otherwise>
                <c:set var="lineClass" value="ArrayCell" />
              </c:otherwise>
            </c:choose>
            <tr>
              <c:if test="${requestScope.currentUserIsAdmin}">
                <td rowspan="2" align="center" valign="top"><input type="checkbox" name="message" value="<c:out value="${message.id}" />" /></td>
              </c:if>
              <td><b><a href="<c:url value="/Rmailinglist/${componentId}/destination/list/message/${message.id}"/>"><c:out value="${message.title}" /></a></b></td>
              <td align="right"><c:choose>
                <c:when test="${message.attachmentsSize <= 0}">&nbsp;</c:when>
                <c:otherwise>
                  <c:out value="${message.attachmentsSizeToDisplay}" />
                  <img src="<c:url value="${attachmentIcon}" />" />
                </c:otherwise>
              </c:choose></td>
              <td rowspan="2" align="center" valign="top" nowrap="nowrap"><c:out value="${message.sender}" /></td>
              <td valign="top" rowspan="2" valign="top" align="right" nowrap="nowrap"><fmt:formatDate value="${message.sentDate}" pattern="dd/MM/yyyy HH:mm:ss" /></td>
            </tr>
            <tr class="<c:out value="${lineClass}"/>">
              <td valign="top" align="left" style="white-space: normal;"><c:out value="${message.summary}" /></td>
            </tr>
          </c:forEach>
          <tr>
            <c:url var="paginationAction" value="/Rmailinglist/${requestScope['componentId']}/list/${requestScope['componentId']}">
              <c:if test="${param.currentYear != null}">
                <c:param name="currentYear" value="${param.currentYear}" />
              </c:if>
              <c:if test="${param.currentMonth != null}">
                <c:param name="currentYear" value="${params.currentMonth}" />
              </c:if>
              <c:if test="${param.orderBy != null}">
                <c:param name="orderBy" value="${param.orderBy}" />
              </c:if>
              <c:if test="${param.ascendant != null}">
                <c:param name="ascendant" value="${param.ascendant}" />
              </c:if>
            </c:url>
            <td colspan="<c:out value="${paginationColspan}"/>"><view:pagination currentPage="${requestScope.currentPage}" nbPages="${requestScope.nbPages}" action="${paginationAction}"
              pageParam="currentPage" /></td>
          </tr>
        </table>
        </td>
      </tr>
    </table>
    <c:if test="${requestScope.currentUserIsAdmin}">
      </form>
    </c:if></center>
  </view:frame>
</view:window>
</body>
</html>

mailinglist/mailinglist-war/src/main/webapp/mailingList/jsp/message.jsp
<%--

    Copyright (C) 2000 - 2018 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="check.jsp"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://www.silverpeas.com/tld/viewGenerator" prefix="view"%>
<c:set var="componentId" value="${requestScope.componentId}" />
<c:set var="sessionController">Silverpeas_MailingList_<c:out value="${componentId}" /></c:set>
<fmt:setLocale value="${sessionScope[sessionController].language}" />
<view:setBundle bundle="${requestScope.resources.multilangBundle}" />
<view:setBundle bundle="${requestScope.resources.iconsBundle}" var="icons" />
<fmt:message key="mailingList.icons.attachmentBig" var="attachmentIcon" bundle="${icons}" />
<html>
<head>
<c:set var="message" value="${requestScope.currentMessage}" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Message</title>
<view:looknfeel />
<script type="text/javascript">
  <c:if test="${(requestScope.currentUserIsAdmin || requestScope.currentUserIsModerator) && ! message.moderated}">
    function deleteMessage(){
      if(confirm('<fmt:message key="mailingList.moderation.delete.confirm"/>')){
        document.moderate.action='<c:url value="/Rmailinglist/${componentId}/message/delete" />';
        document.moderate.submit();
      }
    }
    function moderateMessage(){
      if(confirm('<fmt:message key="mailingList.moderation.moderate.confirm"/>')){
        document.moderate.action='<c:url value="/Rmailinglist/${componentId}/message/put" />';
        document.moderate.submit();
      }
    }
  </c:if>
</script>
</head>
<body>
<c:url value="/Rmailinglist/${componentId}/message/${requestScope.currentMessage.id}" var="messageUrl" />
<c:choose>
  <c:when test="${requestScope.currentFromPath == 'moderation' || requestScope.currentFromPath == 'list' || requestScope.currentFromPath == 'activity'}">
    <c:choose>
      <c:when test="${requestScope.currentFromPath == 'moderation'}">
        <fmt:message key="mailingList.tab.moderation.title" var="browseTitle" />
        <c:url value="/Rmailinglist/${componentId}/moderationList/${componentId}" var="browseUrl" />
      </c:when>
      <c:when test="${requestScope.currentFromPath == 'list'}">
        <fmt:message key="mailingList.tab.list.title" var="browseTitle" />
        <c:url value="/Rmailinglist/${componentId}/list/${componentId}" var="browseUrl" />
      </c:when>
      <c:when test="${requestScope.currentFromPath == 'activity'}">
        <fmt:message key="mailingList.tab.activity.title" var="browseTitle" />
        <c:url value="/Rmailinglist/${componentId}/Main" var="browseUrl" />
      </c:when>
    </c:choose>
    <c:set var="browseBarPath"><a href="<c:out value="${browseUrl}"/>"><c:out value="${browseTitle}" /></a>&nbsp;&gt;&nbsp;<c:out value="${requestScope.currentMessage.title}" /></c:set>
    <view:browseBar>
	  <view:browseBarElt link="${browseUrl}" label="${browseTitle}"  />
	  <view:browseBarElt link="${messageUrl}" label="${requestScope.currentMessage.title}" id="${requestScope.currentMessage.id}"/>
	</view:browseBar>
  </c:when>
  <c:otherwise>
   <view:browseBar>
	  <view:browseBarElt link="${messageUrl}" label="${requestScope.currentMessage.title}"  />
	</view:browseBar>
  </c:otherwise>
</c:choose>
<c:if test="${(requestScope.currentUserIsAdmin || requestScope.currentUserIsModerator) && ! message.moderated}">
  <fmt:message key="mailingList.icons.message.delete" var="deleteMessageIcon" bundle="${icons}" />
  <fmt:message key="mailingList.icons.message.delete.alt" var="deleteMessageAltText" />
  <fmt:message key="mailingList.icons.message.moderate" var="acceptIcon" bundle="${icons}" />
  <fmt:message key="mailingList.icons.message.moderate.alt" var="acceptMessageAltText" />
  <c:url var="deleteIconUrl" value="${deleteMessageIcon}" />
  <c:url var="acceptIconUrl" value="${acceptIcon}" />
  <view:operationPane>
    <view:operation altText="${deleteMessageAltText}" icon="${deleteIconUrl}" action="javascript: deleteMessage();" />
    <view:operation altText="${acceptMessageAltText}" icon="${acceptIconUrl}" action="javascript: moderateMessage();" />
  </view:operationPane>
  <form name="moderate" id="moderate"><input type="hidden" name="message" id="message" value="<c:out value="${message.id}"/>" />"</form>
</c:if>
<view:window>
  <view:frame>
    <c:set var="attachments" value="${requestScope.currentMessageAttachments}" />
    <table id="message" width="100%" cellspacing="2" cellpadding="2" border="0">
      <tr>
        <td class="txtnav" align="left" colspan="2"><c:out value="${message.title}" /></td>
      </tr>
      <tr>
        <td valign="top" width="100%"><c:out value="${message.body}" escapeXml="false" /></td>
        <td valign="top"><c:if test="${not empty attachments}">
          <table id="attachments" class="tableBoard">
            <tbody>
              <tr>
                <td align="center" valign="top"><img src="<c:url value="${attachmentIcon}" />" /></td>
              </tr>
              <c:forEach items="${attachments}" var="attachment">
                <tr>
                  <td align="left" nowrap="nowrap"><img width="20" src="<c:out value="${attachment.icon}"/>" alt="" /> <a target="_blank" id="<c:out value="${attachment.fileName}" />"
                    href="<c:url value="${attachment.url}"/>"><c:out value="${attachment.fileName}" /></a> <a href="<c:url value="${attachment.url}"/>"><img border="0"
                    title="Pour copier le lien vers ce fichier : Clique droit puis 'Copier le raccourci'" alt="Pour copier le lien vers ce fichier : Clique droit puis 'Copier le raccourci'"
                    src="<c:url value="/util/icons/link.gif"/>" /></a> <br />
                  <c:out value="${attachment.displayableSize}" /><br />
                  </td>
                </tr>
              </c:forEach>
            </tbody>
          </table>
        </c:if></td>
      </tr>
      <tr>
        <td colspan="2" align="center" class="txtBaseline"><c:out value="${message.sender}" /> - <fmt:formatDate value="${message.sentDate}" pattern="dd/MM/yyyy HH:mm:ss" /></td>
      </tr>
    </table>
  </view:frame>
</view:window>
</body>
</html>